[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
escrow = "HUk6tTBZdeCVprusZhfzrUEVXo5nzGxVA22y5uVG2tJb"

[programs.devnet]
escrow = "HUk6tTBZdeCVprusZhfzrUEVXo5nzGxVA22y5uVG2tJb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
